export enum ENUM_AUTH_GOOGLE_STATUS_CODE_ERROR {
  AUTH_GOOGLE_TOKEN_INVALID_ERROR = 5600,
}

export enum ENUM_AUTH_GOOGLE_STATUS_CODE_SUCCESS {
  AUTH_GOOGLE_LOGIN_SUCCESS = 5601,
}

export const AUTH_EXCLUDE_API_KEY_META_KEY = 'AuthExcludeApiKeyMetaKey';
